resolver: lts-24.12
# We currently maintain compatibility with 22.39 for transition purposes, but only
# with the ci flag set to false
# resolver: lts-22.39

packages:
- .

extra-deps:
  - github: flipstone/henforcer
    commit: e59f7a252067f649277258704a754348fb6a4a35

  - geohash-1.0.1@sha256:be8bf007f56fae73366c295084b9e1bdc6f50a9c3c435767353f5d18b5d76227,516
  - pollock-0.1.0.3

flags:
  geocoordinate:
    ci: true
